#!/usr/bin/env bash
# Prints "Best school" 10 times with "hi" after the ninth element

counter=1

while [ $counter -le 10 ]
do
	echo "Best School"
	if ((counter == 9))
	then
		echo "Hi"
	fi
	((counter++))
done
