#!/usr/bin/env bash

# Prints "bad luck" on 4th iteration, "good luck" on 8th iteration, otherwise "Best School"

counter=1

while [ $counter -le 10 ]
do
	if ((counter == 4))
	then
		echo "bad luck"
	elif ((counter == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
